commands_restrictions:
  copy:
    conditions:
      - sender=muiolay

pull_request_rules:
  - name: B2 noop
    conditions:
      - -closed
    actions:
      label:
        add:
          - b2-base-touched
