queue_rules:
  - name: default
    queue_conditions:
      - check-success=b2-required-ci
    merge_conditions:
      - check-success=b2-never-green
    merge_method: merge

pull_request_rules:
  - name: B2 queue when required CI is green
    conditions:
      - -closed
      - check-success=b2-required-ci
    actions:
      queue:
        name: default
